name: CI

on:
  push:
    branches: [master, main, trunk]
  pull_request:
    branches: [master, main, trunk]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      #   with:
      #     config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          persist-credentials: false
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # 3.2.1
        with:
          hugo-version: "0.148.2"
          # extended: true
      - name: Build
        run: hugo -b http://open-services.net/ -t oslc
